In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('NFL.csv')
df = df.drop_duplicates()

/var/folders/0s/s2qqdkfs7_b9yv8pvrv2djp00000gn/T/ipykernel_11283/1922676786.py:1: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('NFL.csv')

In [7]:
df = df.iloc[:, 0:9]

In [8]:
df

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0
...,...,...,...,...,...,...,...,...,...
407683,2017-12-31,2017123101,29,4,NaN,00:28,1,28.0,4.0
407684,2017-12-31,2017123101,29,4,3.0,00:28,1,28.0,0.0
407685,2017-12-31,2017123101,29,4,4.0,00:24,1,24.0,4.0
407686,2017-12-31,2017123101,30,4,1.0,00:14,1,14.0,10.0
407687,2017-12-31,2017123101,30,4,NaN,00:00,0,0.0,14.0

In [18]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df_filtered = df[(df['Date'].dt.year >= 2010) & (df['Date'].dt.year <= 2015)]
df_filtered = df_filtered.reset_index(drop=True)
df_filtered

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2010-01-03,2010010300,1,1,NaN,15:00,15,3600.0,0.0
1,2010-01-03,2010010300,1,1,1.0,14:53,15,3593.0,7.0
2,2010-01-03,2010010300,1,1,2.0,14:13,15,3553.0,40.0
3,2010-01-03,2010010300,1,1,3.0,13:45,14,3525.0,28.0
4,2010-01-03,2010010300,1,1,4.0,13:06,14,3486.0,39.0
...,...,...,...,...,...,...,...,...,...
271954,2015-12-28,2015122800,21,5,4.0,10:05,11,-295.0,5.0
271955,2015-12-28,2015122800,22,5,NaN,10:00,10,-300.0,5.0
271956,2015-12-28,2015122800,22,5,1.0,09:53,10,-307.0,7.0
271957,2015-12-28,2015122800,22,5,NaN,09:48,10,-312.0,5.0
271958,2015-12-28,2015122800,22,5,2.0,09:48,10,-312.0,0.0

In [20]:
df_filtered.fillna("")

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2010-01-03,2010010300,1,1,,15:00,15,3600.0,0.0
1,2010-01-03,2010010300,1,1,1.0,14:53,15,3593.0,7.0
2,2010-01-03,2010010300,1,1,2.0,14:13,15,3553.0,40.0
3,2010-01-03,2010010300,1,1,3.0,13:45,14,3525.0,28.0
4,2010-01-03,2010010300,1,1,4.0,13:06,14,3486.0,39.0
...,...,...,...,...,...,...,...,...,...
271954,2015-12-28,2015122800,21,5,4.0,10:05,11,-295.0,5.0
271955,2015-12-28,2015122800,22,5,,10:00,10,-300.0,5.0
271956,2015-12-28,2015122800,22,5,1.0,09:53,10,-307.0,7.0
271957,2015-12-28,2015122800,22,5,,09:48,10,-312.0,5.0
271958,2015-12-28,2015122800,22,5,2.0,09:48,10,-312.0,0.0

In [21]:
for x in df_filtered.index:
    if df_filtered.loc[x, 'TimeSecs'] <= 0:
        df_filtered.drop(x, inplace=True)
df_filtered

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2010-01-03,2010010300,1,1,NaN,15:00,15,3600.0,0.0
1,2010-01-03,2010010300,1,1,1.0,14:53,15,3593.0,7.0
2,2010-01-03,2010010300,1,1,2.0,14:13,15,3553.0,40.0
3,2010-01-03,2010010300,1,1,3.0,13:45,14,3525.0,28.0
4,2010-01-03,2010010300,1,1,4.0,13:06,14,3486.0,39.0
...,...,...,...,...,...,...,...,...,...
271934,2015-12-28,2015122800,20,4,1.0,00:27,1,27.0,32.0
271935,2015-12-28,2015122800,20,4,NaN,00:23,1,23.0,4.0
271936,2015-12-28,2015122800,20,4,2.0,00:23,1,23.0,0.0
271937,2015-12-28,2015122800,20,4,NaN,00:04,1,4.0,19.0
271938,2015-12-28,2015122800,20,4,3.0,00:04,1,4.0,0.0

In [22]:
df_filtered = df_filtered.reset_index(drop=True)
df_filtered

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2010-01-03,2010010300,1,1,NaN,15:00,15,3600.0,0.0
1,2010-01-03,2010010300,1,1,1.0,14:53,15,3593.0,7.0
2,2010-01-03,2010010300,1,1,2.0,14:13,15,3553.0,40.0
3,2010-01-03,2010010300,1,1,3.0,13:45,14,3525.0,28.0
4,2010-01-03,2010010300,1,1,4.0,13:06,14,3486.0,39.0
...,...,...,...,...,...,...,...,...,...
268594,2015-12-28,2015122800,20,4,1.0,00:27,1,27.0,32.0
268595,2015-12-28,2015122800,20,4,NaN,00:23,1,23.0,4.0
268596,2015-12-28,2015122800,20,4,2.0,00:23,1,23.0,0.0
268597,2015-12-28,2015122800,20,4,NaN,00:04,1,4.0,19.0
268598,2015-12-28,2015122800,20,4,3.0,00:04,1,4.0,0.0

In [33]:
df_filtered['down'] = df_filtered['down'].fillna("")

In [34]:
df_filtered

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff
0,2010-01-03,2010010300,1,1,,15:00,15,3600.0,0.0
1,2010-01-03,2010010300,1,1,1.0,14:53,15,3593.0,7.0
2,2010-01-03,2010010300,1,1,2.0,14:13,15,3553.0,40.0
3,2010-01-03,2010010300,1,1,3.0,13:45,14,3525.0,28.0
4,2010-01-03,2010010300,1,1,4.0,13:06,14,3486.0,39.0
...,...,...,...,...,...,...,...,...,...
268594,2015-12-28,2015122800,20,4,1.0,00:27,1,27.0,32.0
268595,2015-12-28,2015122800,20,4,,00:23,1,23.0,4.0
268596,2015-12-28,2015122800,20,4,2.0,00:23,1,23.0,0.0
268597,2015-12-28,2015122800,20,4,,00:04,1,4.0,19.0
268598,2015-12-28,2015122800,20,4,3.0,00:04,1,4.0,0.0