In [5]:
import pandas as pd

In [38]:
df = pd.read_csv('dirty_data.csv')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [39]:
df['Rank'] = df.index + 1
df = df.drop('Peak', axis=1)
df

,Rank,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [40]:
df = df.drop('All Time Peak', axis=1)

In [41]:
df.columns = df.columns.str.strip()  # remove leading/trailing spaces
df.columns = df.columns.str.strip().str.replace('\xa0','')
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [42]:
df['Actualgross'] = df['Actualgross'].str.replace('[^0-9$]', '', regex=True)

In [43]:
df['Actualgross'] = df['Actualgross'].str.replace('$','', regex=False).str.replace(',','', regex=False)
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,780000000,"$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,579800000,"$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,411000000,"$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,397300000,"$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,345675146,"$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,305158363,"$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,280000000,"$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,257600000,"$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,256084556,"$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,250400000,"$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,229100000,"$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,227400000,"$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,204000000,"$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,200000000,"$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,194000000,"$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,184000000,"$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,170000000,"$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,169800000,"$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,167700000,"$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,150000000,"$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [44]:
df['Actualgross'] = df['Actualgross'].apply(lambda x: f"{int(x):,}")
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,"579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,"397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,"257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,"256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"229,100,000","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,"194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"167,700,000","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [45]:
df['Adjustedgross (in 2022 dollars)'] = df['Adjustedgross (in 2022 dollars)'].str.replace('$','', regex=False).str.replace(',','', regex=False)
df['Adjustedgross (in 2022 dollars)'] = df['Adjustedgross (in 2022 dollars)'].apply(lambda x: f"{int(x):,}")
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,"257,600,000","257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [46]:
df['Tour title'] = df['Tour title'].str.replace(r'[\u2020\[\]].*$', '', regex=True).str.strip()
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,2023–2024,56,"$13,928,571",[1]
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour ‡,2008–2009,85,"$4,835,294",[6]
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,"257,600,000","257,600,000",Pink,Summer Carnival,2023–2024,41,"$6,282,927",[12]
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour ‡,2002–2005,325,"$615,385",[20]
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [48]:
df['Tour title'] = df['Tour title'].str.split('*').str[0].str.strip()
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,2023–2024,56,"$13,928,571",[1]
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour,2008–2009,85,"$4,835,294",[6]
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,8,"257,600,000","257,600,000",Pink,Summer Carnival,2023–2024,41,"$6,282,927",[12]
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour,2009–2011,203,"$1,118,227",[18]
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour,2002–2005,325,"$615,385",[20]
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [50]:
df = df.drop('Ref.', axis=1)
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,2023–2024,56,"$13,928,571"
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571"
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour,2008–2009,85,"$4,835,294"
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795"
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173"
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709"
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405"
7,8,"257,600,000","257,600,000",Pink,Summer Carnival,2023–2024,41,"$6,282,927"
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215"
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882"
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606"
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour,2009–2011,203,"$1,118,227"
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993"
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour,2002–2005,325,"$615,385"
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333"
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775"
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694"
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732"
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950"
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186"

In [52]:
df['Average gross'] = df['Average gross'].str.replace('[^0-9$]', '', regex=True)
df['Average gross'] = df['Average gross'].str.replace('$','', regex=False).str.replace(',','', regex=False)
df['Average gross'] = df['Average gross'].apply(lambda x: f"{int(x):,}")
df

,Rank,Actualgross,Adjustedgross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,2023–2024,56,"13,928,571"
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"10,353,571"
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour,2008–2009,85,"4,835,294"
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"2,546,795"
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"6,522,173"
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"3,467,709"
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"2,137,405"
7,8,"257,600,000","257,600,000",Pink,Summer Carnival,2023–2024,41,"6,282,927"
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"5,226,215"
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"2,945,882"
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"1,735,606"
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour,2009–2011,203,"1,118,227"
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"1,350,993"
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour,2002–2005,325,"615,385"
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"3,233,333"
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"1,295,775"
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"1,734,694"
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"2,070,732"
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"1,385,950"
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"1,744,186"

In [53]:
df.columns = ['Rank', 'Actual Gross', 'Adjusted Gross', 'Artist', 'Tour Title', 'Year(s)', 'Shows', 'AverageGross']
df

,Rank,Actual Gross,Adjusted Gross,Artist,Tour Title,Year(s),Shows,AverageGross
0,1,"780,000,000","780,000,000",Taylor Swift,The Eras Tour,2023–2024,56,"13,928,571"
1,2,"579,800,000","579,800,000",Beyoncé,Renaissance World Tour,2023,56,"10,353,571"
2,3,"411,000,000","560,622,615",Madonna,Sticky & Sweet Tour,2008–2009,85,"4,835,294"
3,4,"397,300,000","454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"2,546,795"
4,5,"345,675,146","402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"6,522,173"
5,6,"305,158,363","388,978,496",Madonna,The MDNA Tour,2012,88,"3,467,709"
6,7,"280,000,000","381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"2,137,405"
7,8,"257,600,000","257,600,000",Pink,Summer Carnival,2023–2024,41,"6,282,927"
8,9,"256,084,556","312,258,401",Beyoncé,The Formation World Tour,2016,49,"5,226,215"
9,10,"250,400,000","309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"2,945,882"
10,11,"229,100,000","283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"1,735,606"
11,12,"227,400,000","295,301,479",Lady Gaga,The Monster Ball Tour,2009–2011,203,"1,118,227"
12,13,"204,000,000","251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"1,350,993"
13,14,"200,000,000","299,676,265",Cher,Living Proof: The Farewell Tour,2002–2005,325,"615,385"
14,15,"194,000,000","281,617,035",Madonna,Confessions Tour,2006,60,"3,233,333"
15,16,"184,000,000","227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"1,295,775"
16,17,"170,000,000","213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"1,734,694"
17,18,"169,800,000","207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"2,070,732"
18,19,"167,700,000","204,486,106",Adele,Adele Live 2016,2016–2017,121,"1,385,950"
19,20,"150,000,000","185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"1,744,186"

In [54]:
df.to_csv('cleaned_tours.csv', index=False)